### PR TITLE
Fix HMR bugs

### PR DESCRIPTION
**Pull request by jacksteamdev**
This PR includes a couple of quality-of-life fixes for HMR.

1. Automatically ignores `build.outDir` for server, so HMR doesn't trigger a full reload when the file writer writes.
2. Fixes flaky HMR updates for content scripts; Tailwind should work fine now.

### CODE REVIEW

**Comment by jacksteamdev** [comment]
Closes #274

**Comment by jacksteamdev** [comment]
Closes #288

**Comment by 101arrowz** [comment]
Hey @jacksteamdev, sorry to barge in on this PR but I'm working on Parcel's implementation of Manifest V3 HMR and I'm wondering how you're getting around the Chromium bug causing `localhost` to be banned in content security policy.

I noticed you added [this section](https://github.com/crxjs/chrome-extension-tools/blob/a1e27280c5ec8e2b2ad63a4995f8d3bcdf9758d4/packages/vite-plugin/src/client/es/hmr-client-worker.ts#L18-L51) to force the content scripts, options pages, etc. to fetch from the server rather than from the extension on the disk, but when you hot-reload the background service worker the fetch interceptor obviously doesn't work. In fact as far as I can tell the only way to download dynamic scripts in background SW is to `importScripts(url)` (or `import(url)` for module service workers, though this is also broken because `import()` is for now still banned in service workers). Neither of these can be intercepted.

So is it true that for the time being background service worker hot reload is impossible?

**Comment by jacksteamdev** [comment]
> So is it true that for the time being background service worker hot reload is impossible?

@101arrowz As I understand it, module imports for service workers are different; it's kind of synchronous, so async things like dynamic import and top-level await don't work. I'm using `chrome.runtime.reload()` to force a full extension reload for background changes.

**Pull request merged**
