### PR TITLE
[Vite Plugin] Fix vite manifest location

### PR DESCRIPTION
**Pull request by ale-ben**
This should solve https://github.com/crxjs/chrome-extension-tools/issues/836

According to [Vite documentation](https://vitejs.dev/guide/backend-integration):
> For production: after running vite build, a .vite/manifest.json file will be generated alongside other asset files.

Right now, when building, the plugin tries to find a vite manifest without considering the `.vite` folder:
https://github.com/crxjs/chrome-extension-tools/blob/20faa1590032ef90b4588dea06ca7610a4483248/packages/vite-plugin/src/node/plugin-webAccessibleResources.ts#L105-L108

As suggested here (https://github.com/crxjs/chrome-extension-tools/issues/836#issuecomment-1830652912), replacing `manifest.json` with `.vite/manifest.json` solves the build error.

### CODE REVIEW

**Comment by kaminskypavel** [comment]
any plans on merging?

**Comment by ale-ben** [comment]
Would be nice to have any feedback on this...
If there are problems I can fix them but I need it merged as well

**Comment by kaminskypavel** [comment]
> Would be nice to have any feedback on this... If there are problems I can fix them but I would like to see it merged as well

this will allow upgrading to Vite@5, am I correct?

**Comment by ale-ben** [comment]
Honestly, I have no idea...
I just had the same problems described here https://github.com/crxjs/chrome-extension-tools/issues/836 and, after reading a bit of Vite documentation, I identified where the problem was and fixed it (I think so at least)

**Comment by ale-ben** [comment]
@kaminskypavel Just noticed something, I am already using Vite@5...

Screenshot 2023-12-19 at 09 58 00

**Comment by kaminskypavel** [comment]
@jacksteamdev @AmySteam what do you guys think?

**Comment by nandanito** [comment]
@ale-ben I'm still getting the same following error, while using `vite@5.0.10` with `vite-plugin@2.0.0-beta.21`.
`[crx:web-accessible-resources] TypeError: OutputBundle["manifest.json"] is undefined.`

The upgrading to 5.0.x is not working.

**Comment by ale-ben** [comment]
@nandanito [this](https://github.com/ale-ben/Teal-Owl/tree/10e58d879781111c78eee1febfb39399975cd496/apps/reader) is the project I'm testing with.

Just to be on the safe side, I rebuilt the vite plugin from my main branch and manually put it in my project. This is the build outputs:
Vite plugin:
Screenshot 2023-12-20 at 10 25 35
My project (with dist folder manually replaced with build output):
Screenshot 2023-12-20 at 10 25 45

Can you provide an example of when it doesn't work?

**Comment by khs6666** [comment]
https://play.google.com/store/apps/details?id=com.kakao.talk&pcampaignid=web_share

**Comment by nandanito** [comment]
@ale-ben Here is the [repo](https://github.com/nandanito/browser-extension-template-bun-vite-react) where it is not working.

I think merging your commit in the next release might solve the issue (also discussed [here](https://github.com/crxjs/chrome-extension-tools/issues/836)).

**Review by jacksteamdev — COMMENTED** [review]
@ale-ben Thanks for the PR! Awesome research and deduction to get this working with Vite 5! 🌟

It looks like this is a breaking change for Vite 4, but maybe that's not a big deal? We could release this in one of two ways:
1. Major version bump and only support Vite 5+
2. Make this PR backwards compatible

What makes the most sense to everyone?

I'm going to promote the beta to latest on NPM in the next few weeks, so maybe option one is most maintainable option.

**Comment by jacksteamdev** [comment]
Sorry for the slow feedback, I've been slammed at work for the last couple of months as we were completing a major product launch.

**Comment by kaminskypavel** [comment]
IMHO, breaking changes should be a last resort, especially if this can be
avoided with a simple if/then statement.

**Comment by ale-ben** [comment]
This _should_ provide compatibility for both Vite <=4 and Vite >4.
Let me know if I missed something.

**Comment by kaminskypavel** [comment]
@jacksteamdev can we merge this? it is blocking vite upgrade

**Comment by jacksteamdev** [comment]
It seems like the tests are broken, but I don't think it's this PR. I'm working to fix them now, will update later.

**Review by jacksteamdev — APPROVED** [review]
LGTM!

**Comment by khs6666** [comment]
________________________________
보낸 사람: Jack Steam ***@***.***>
보낸 날짜: 2024년 1월 11일 목요일 08:30
받는 사람: crxjs/chrome-extension-tools ***@***.***>
참조: khs6666 ***@***.***>; Comment ***@***.***>
제목: Re: [crxjs/chrome-extension-tools] [Vite Plugin] Fix vite manifest location (PR #841)


Merged #841<https://github.com/crxjs/chrome-extension-tools/pull/841> into main.

**Comment by khs6666** [comment]
________________________________
보낸 사람: khs6666 ***@***.***>
보낸 날짜: 2024년 1월 16일 화요일 02:20
받는 사람: crxjs/chrome-extension-tools ***@***.***>
참조: khs6666 ***@***.***>; Your activity ***@***.***>
제목: Re: [crxjs/chrome-extension-tools] [Vite Plugin] Fix vite manifest location (PR #841)


________________________________
보낸 사람: Jack Steam ***@***.***>
보낸 날짜: 2024년 1월 11일 목요일 08:30
받는 사람: crxjs/chrome-extension-tools ***@***.***>
참조: khs6666 ***@***.***>; Comment ***@***.***>
제목: Re: [crxjs/chrome-extension-tools] [Vite Plugin] Fix vite manifest location (PR #841)


Merged #841<https://github.com/crxjs/chrome-extension-tools/pull/841> into main.

**Comment by khs6666** [comment]
________________________________
보낸 사람: khs6666 ***@***.***>
보낸 날짜: 2024년 1월 16일 화요일 02:48
받는 사람: crxjs/chrome-extension-tools ***@***.***>
참조: khs6666 ***@***.***>; Your activity ***@***.***>
제목: Re: [crxjs/chrome-extension-tools] [Vite Plugin] Fix vite manifest location (PR #841)


________________________________
보낸 사람: khs6666 ***@***.***>
보낸 날짜: 2024년 1월 16일 화요일 02:20
받는 사람: crxjs/chrome-extension-tools ***@***.***>
참조: khs6666 ***@***.***>; Your activity ***@***.***>
제목: Re: [crxjs/chrome-extension-tools] [Vite Plugin] Fix vite manifest location (PR #841)


________________________________
보낸 사람: Jack Steam ***@***.***>
보낸 날짜: 2024년 1월 11일 목요일 08:30
받는 사람: crxjs/chrome-extension-tools ***@***.***>
참조: khs6666 ***@***.***>; Comment ***@***.***>
제목: Re: [crxjs/chrome-extension-tools] [Vite Plugin] Fix vite manifest location (PR #841)


Merged #841<https://github.com/crxjs/chrome-extension-tools/pull/841> into main.

**Comment by khs6666** [comment]
________________________________
보낸 사람: khs6666 ***@***.***>
보낸 날짜: 2024년 1월 16일 화요일 03:17
받는 사람: crxjs/chrome-extension-tools ***@***.***>
참조: khs6666 ***@***.***>; Your activity ***@***.***>
제목: Re: [crxjs/chrome-extension-tools] [Vite Plugin] Fix vite manifest location (PR #841)


________________________________
보낸 사람: khs6666 ***@***.***>
보낸 날짜: 2024년 1월 16일 화요일 02:48
받는 사람: crxjs/chrome-extension-tools ***@***.***>
참조: khs6666 ***@***.***>; Your activity ***@***.***>
제목: Re: [crxjs/chrome-extension-tools] [Vite Plugin] Fix vite manifest location (PR #841)


________________________________
보낸 사람: khs6666 ***@***.***>
보낸 날짜: 2024년 1월 16일 화요일 02:20
받는 사람: crxjs/chrome-extension-tools ***@***.***>
참조: khs6666 ***@***.***>; Your activity ***@***.***>
제목: Re: [crxjs/chrome-extension-tools] [Vite Plugin] Fix vite manifest location (PR #841)


________________________________
보낸 사람: Jack Steam ***@***.***>
보낸 날짜: 2024년 1월 11일 목요일 08:30
받는 사람: crxjs/chrome-extension-tools ***@***.***>
참조: khs6666 ***@***.***>; Comment ***@***.***>
제목: Re: [crxjs/chrome-extension-tools] [Vite Plugin] Fix vite manifest location (PR #841)


Merged #841<https://github.com/crxjs/chrome-extension-tools/pull/841> into main.

**Pull request merged**
