### PR TITLE
Add Side Panel page to the html files list

### PR DESCRIPTION
**Pull request by somaka**
Allows using the sidePanel API https://developer.chrome.com/docs/extensions/reference/sidePanel/

### CODE REVIEW

**Comment by JoeyDoey** [comment]
Love to see it!!!

**Comment by datermine** [comment]
@somaka -- thanks for this!  I'm not a contributor to this repo, just started playing with it, so apologies if this is a dumb question, but: Does this schema file need to be updated as well?
https://github.com/crxjs/chrome-extension-tools/blob/main/schema/manifest-v3.schema.json

image

**Comment by datermine** [comment]
> @somaka -- thanks for this! I'm not a contributor to this repo, just started playing with it, so apologies if this is a dumb question, but: Does this schema file need to be updated as well? https://github.com/crxjs/chrome-extension-tools/blob/main/schema/manifest-v3.schema.json
> 
> image

And maybe also here? 
https://github.com/crxjs/chrome-extension-tools/blob/main/schema/manifest-v3.schema.json#L152

**Comment by datermine** [comment]
What's it take to get this merged?

**Comment by somaka** [comment]
> What's it take to get this merged?

Depends on maintainers. The change look small & obvious. Also, the sidePanel is already in mainstream Chrome releases (not sure if Edge is going to pick it up soon though).

I'm happy to make any additional changes if needed.

**Comment by jacksteamdev** [comment]
Looks good! Sorry for the delayed merge, I really appreciate the contribution 👍

**Comment by lenaggar** [comment]
Hey, Sorry if the answer to my question sounds obvious,
but starting of which version is this modification part of?

**Pull request merged**
