### PR TITLE
docs: added Vue use cases

### PR DESCRIPTION
**Pull request by xianjianlf2**
I found that the documentation lacks information on how to use `content-script` of `vue`.

### CODE REVIEW

**Comment by Toumash** [comment]
Looks like its ready to be merged. Just a copy of the page from react + vue code.

**Comment by xianjianlf2** [comment]
The document lacks an example of a `content script` using `vue` syntax, similar to the [react content script](https://crxjs.dev/vite-plugin/getting-started/react/add-content-script). Here is the relevant content added. Since the syntax of `react 18` is similar to that of `vue`, but in Vue, examples are written on `SFC` components.

> Looks like its ready to be merged. Just a copy of the page from react + vue code.

**Review by jacksteamdev — APPROVED** [review]
@xianjianlf2 Thanks 🙏

**Comment by jacksteamdev** [comment]
@Toumash thanks for the review!

**Pull request merged**
