### PR TITLE
feat: add compatibility mode for Firefox

### PR DESCRIPTION
**Pull request by winstxnhdw**
See #644.

The original author seems to be inactive.

### CODE REVIEW

**Comment by jhholm** [comment]
Looks pretty good to me, when I tried to fix the linting issue my fix for plugin-manigest.ts was exactly the same. My proposed solution for files.ts is a bit different, though your should work too.

```
// Chromium
const serviceWorker = manifest.background && "service_worker" in manifest.background && manifest.background.service_worker;
// Firefox
const backgroundScripts = manifest.background && "scripts" in manifest.background && manifest.background.scripts;
// Choose either Firefox or Chromium
const background = serviceWorker ? [serviceWorker].filter(isString) : backgroundScripts ? backgroundScripts.filter(isString) : [];
```

And thus changed return to include **background** . So it would provide either serviceworker or backgroundscript depending on the browser.

**Comment by winstxnhdw** [comment]
> Looks pretty good to me. When I had my look to fix the linting issue my fix for **plugin-manigest.ts** was exactly the same. My proposed solution for **files.ts** is a bit different, though your should work too if not using firefox background scripts.
> 
> ```
> // Chromium
> const serviceWorker = manifest.background && "service_worker" in manifest.background && manifest.background.service_worker;
> // Firefox
> const backgroundScripts = manifest.background && "scripts" in manifest.background && manifest.background.scripts;
> // Choose either Firefox or Chromium
> const background = serviceWorker ? [serviceWorker].filter(isString) : backgroundScripts ? backgroundScripts.filter(isString) : [];
> ```
> 
> And thus changed return to send **background** as is. So it would provide either serviceworker or backgroundscript depending on the browser.

Would you like to contribute this? I am pretty responsive..

**Comment by jhholm** [comment]
Created a pull request to your fork

**Comment by SaltyCucumber** [comment]
Tried it out, running into this issue on Firefox dev, in Chrome dev everything is fine

Screenshot 2023-09-15 at 20 46 39

**Comment by winstxnhdw** [comment]
Are you trying to HMR? As stated in the referenced PR, HMR will not work on Firefox.

**Comment by SaltyCucumber** [comment]
> Are you trying to HMR? As stated in the referenced PR, HMR will not work on Firefox.

You are correct, my bad. The prod build went through ok

**Comment by Chimildic** [comment]
How to apply to version from [npm](https://www.npmjs.com/package/@crxjs/vite-plugin)?

**Comment by winstxnhdw** [comment]
Wait for the maintainers to come back from their vacation 😂

**Comment by JoeyDoey** [comment]
this looks great! good work 🚀

**Comment by jacksteamdev** [comment]
@winstxnhdw @laptou This looks great, I'm happy we finally have some Firefox support!

> Wait for the maintainers to return from their vacation 😂

Everyone, thanks for your patience 🙏 The startup I work for pivoted earlier this year, and I haven't gotten a break since. We're looking into finding a maintainer to help the community.

**Comment by jacksteamdev** [comment]
This was released on NPM https://www.npmjs.com/package/@crxjs/vite-plugin/v/2.0.0-beta.19

**Comment by Chimildic** [comment]
Anyone try to use last release on npm? When I build, plugin create `service-worker-loader.js` file with one line `import './src/background/background.ts'` without any background code.
```
// manifest
"background": {
  "scripts": ["src/background/background.ts"],
},

// vite.config.ts
plugins: [crx({ manifest, browser: 'firefox' })]
```

**Comment by SaltyCucumber** [comment]
> Anyone try to use last release on npm? When I build, plugin create `service-worker-loader.js` file with one line `import './src/background/background.ts'` without any background code.

Yes, had the same issue

was debugging that today and made a PR with a fix https://github.com/crxjs/chrome-extension-tools/pull/790

**Comment by farzadmf** [comment]
Hey everyone, I was wondering if anyone has managed to use this tool (`crxjs` I mean) to build a Firefox plugin.

For me, trying to incorporate this tool into an existing plugin, currently being built with Webpack:
- Dev mode is _completely_ broken (because of all the security and CSP (content security policy) things.
- "Production" mode (`vite build`) is also broken.

**Pull request merged**
