### PR TITLE
fix: workaround for the issue with chrome.runtime.getURL introduced in Chrome 130 causing CSP rejecting script due to different origin (GUID instead of chrome extension id)

### PR DESCRIPTION
**Pull request by onv**
fix: workaround for the issue with chrome.runtime.getURL introduced in Chrome 130 causing CSP rejecting script due to different origin (GUID instead of chrome extension id)

Starting Chrome 130 `use_dynamic_url` has taken an effect and as a result chrome.runtime.getURL(path) now returns url with random GUID `chrome-extension://1d4b08e1-f2c5-48e5-839d-32c125e7a989/${path}` instead of `chrome-extension://${chrome.runtime.id}/${path}`
Setting `use_dynamic_url` to `false` or replacing chrome.runtime.getURL() with template string `chrome-extension://${chrome.runtime.id}/${path}` solves the issue.

The related [issue](https://github.com/crxjs/chrome-extension-tools/issues/927)

image (14)

### CODE REVIEW

**Comment by onv** [comment]
@jacksteamdev could you please take a look?

**Comment by goodideagiver** [comment]
I tried to use this changes in `patch-package` and manually editing `vite-plugin/node_modules/dist` but for me it didn't fix the issue

```diff --git a/node_modules/@crxjs/vite-plugin/dist/index.mjs b/node_modules/@crxjs/vite-plugin/dist/index.mjs
index c543f3e..654ed0d 100644
--- a/node_modules/@crxjs/vite-plugin/dist/index.mjs
+++ b/node_modules/@crxjs/vite-plugin/dist/index.mjs
@@ -1805,7 +1805,7 @@ function compileFileResources(fileName, {
 const defineManifest = (manifest) => manifest;
 const defineDynamicResource = ({
   matches = ["http://*/*", "https://*/*"],
-  use_dynamic_url = true
+  use_dynamic_url = false
 }) => ({
   matches,
   resources: [DYNAMIC_RESOURCE],
@@ -1839,7 +1839,7 @@ const pluginWebAccessibleResources = () => {
           // all resources are web accessible
           resources: ["**/*", "*"],
           // change the extension origin on every reload
-          use_dynamic_url: true
+          use_dynamic_url: false
         };
         if (browser === "firefox") {
           delete war.use_dynamic_url;
```

**Comment by pietrofxq** [comment]
> I tried to use this changes in `patch-package` and manually editing `vite-plugin/node_modules/dist` but for me it didn't fix the issue
> 
> ```diff
> index c543f3e..654ed0d 100644
> --- a/node_modules/@crxjs/vite-plugin/dist/index.mjs
> +++ b/node_modules/@crxjs/vite-plugin/dist/index.mjs
> @@ -1805,7 +1805,7 @@ function compileFileResources(fileName, {
>  const defineManifest = (manifest) => manifest;
>  const defineDynamicResource = ({
>    matches = ["http://*/*", "https://*/*"],
> -  use_dynamic_url = true
> +  use_dynamic_url = false
>  }) => ({
>    matches,
>    resources: [DYNAMIC_RESOURCE],
> @@ -1839,7 +1839,7 @@ const pluginWebAccessibleResources = () => {
>            // all resources are web accessible
>            resources: ["**/*", "*"],
>            // change the extension origin on every reload
> -          use_dynamic_url: true
> +          use_dynamic_url: false
>          };
>          if (browser === "firefox") {
>            delete war.use_dynamic_url;
> ```

I think you updated the wrong lines. You should update the values on lines 1842 and 1924

**Review by canastro — APPROVED** [review]

**Comment by tance77** [comment]
We're excited about this patch. Our Extension is dead in the water till this is merged and deployed.

**Comment by pietrofxq** [comment]
@tance77 in the meantime you can patch the tool with patch-package, check https://github.com/crxjs/chrome-extension-tools/issues/918#issuecomment-2417036333

**Comment by mr-menno** [comment]
This is also in issue: https://github.com/crxjs/chrome-extension-tools/issues/929

The simplest fix to get this working again is updating:
`const ownOrigin = new URL(chrome.runtime.getURL(\"/\")).origin;`
to
`const ownOrigin = 'chrome-extension://'+chrome.runtime.id;`
in
`packages/vite-plugin/src/client/es/hmr-client-worker.ts`

**Comment by mr-menno** [comment]
Thanks @onv !  

When can this PR be merged and released?  A lot of dev is at a standstill without manual patching.

**Comment by onv** [comment]
@jacksteamdev, can this PR be merged? Looks like I still need an approval from maintainer. Thanks.

**Review by jacksteamdev — APPROVED** [review]
Thanks @onv for putting this together!

**Comment by jacksteamdev** [comment]
This landed in [2.0.0-beta.26](https://www.npmjs.com/package/@crxjs/vite-plugin/v/2.0.0-beta.26)

**Comment by tance77** [comment]
2.0.0-beta26
seems to replace my background serverice worker path with `service-worker-loader.js` and that doesn't seem to exist for me.

**Comment by jacksteamdev** [comment]
> 2.0.0-beta26 seems to replace my background serverice worker path with `service-worker-loader.js` and that doesn't seem to exist for me.

@tance77 If this is still happening for you, please create an issue so we can reproduce it.

**Comment by rahulbansal16** [comment]
> This landed in [2.0.0-beta.26](https://www.npmjs.com/package/@crxjs/vite-plugin/v/2.0.0-beta.26)

What is the version of Vite to use for this?
I am using the  5.4.6 and I'm getting the errors about import _vite_plugin.crx is not a function.
image

```js
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { crx } from '@crxjs/vite-plugin'
import manifest from './manifest.json'

export default defineConfig({
  plugins: [
    react(),
    crx({ manifest }),
  ],
})
```

Tried this configs https://github.com/crxjs/chrome-extension-tools/issues/939#issuecomment-2440823335 but the error is persistent.

@jacksteamdev

**Comment by rahulbansal16** [comment]
Anyone able to resolve the issues of https://github.com/crxjs/chrome-extension-tools/issues/939#issuecomment-2440823335

**Pull request merged**
