### PR TITLE
Add match_origin_as_fallback to manifest-v3.schema.json

### PR DESCRIPTION
**Pull request by hovavo**
See https://developer.chrome.com/docs/extensions/develop/concepts/content-scripts#injecting-in-related-frames

### CODE REVIEW

**Comment by jacksteamdev** [comment]
Closes #845

**Review by jacksteamdev — APPROVED** [review]
Thanks for the PR!

**Comment by xiata** [comment]
Curious, this touches `packages/rollup-plugin/schema/manifest-v3.schema.json` but does not touch `schema/manifest-v3.schema.json`. Is that intentional?

**Comment by hovavo** [comment]
Hmm probably not. I must have missed that and for my needs (a rollup project) that one change did the job.

**Pull request merged**
